package com.nparo.TaskMaster.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "taskmaster")
public class Tasks {
  private String id;
  private String title;
  private String description;
  private String status;
  
  public Tasks(){}
  
  public Tasks(String id, String title, String description, String status) {
    this.id = id;
    this.title = title;
    this.description = description;
    this.status = status;
  }
  
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId () {
    return id;
  }
  
  public void setId (String id) {
    this.id = id;
  }
  
  @DynamoDBAttribute
  public String getTitle () {
    return title;
  }
  
  public void setTitle (String title) {
    this.title = title;
  }
  
  @DynamoDBAttribute
  public String getDescription () {
    return description;
  }
  
  public void setDescription (String description) {
    this.description = description;
  }
  
  @DynamoDBAttribute
  public String getStatus () {
    return status;
  }
  
  public void setStatus (String status) {
    this.status = status;
  }
}
